version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.2-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  build:
    docker:
      - image: circleci/node:12.2

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm run build:package

      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    docker:
      - image: circleci/node:12.2

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      # Add the public deploy key from the repository
      # and call checkout to ensure git uses ssh not https
      - add_ssh_keys:
          fingerprints:
            - "cf:9f:64:b3:02:33:f3:f9:13:9e:86:2c:40:f1:cf:66"
      - checkout

      # Update package.json version
      - run: npm version $CIRCLE_TAG && git push origin HEAD:master
      - run: npm run build:package
      - run: npm run deploy:documentation
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/repo/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  test-build-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore:
                - master
      - build:
          requires:
            - test
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore:
                - master
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
